### ISSUE TITLE
Installer options?

### ISSUE THREAD

**Issue by JonnyTech** [Mexit/MultiOS-USB#1]
> Usage: sudo $scriptname [options] device [data_size]

What `options` are available for the installer? I cannot find any documentation.

**Comment by Mexit** [comment]
Run `./installer.sh` - all options will be displayed.
You can set the file system (-fs), your own folder name (-d) with configuration files.

**Comment by JonnyTech** [comment]
Thanks.

```
$ ./installer.sh 

MultiOS-USB installer

Usage: sudo installer.sh [options] device [data_size]

 	device				Device to install (e.g. /dev/sdb)
 	data_size			Data partition size (e.g. 5G)
 	-fs, --fs_type			Filesystem type for the data partition [ext2|ext3|ext4|fat32|exfat|ntfs] (default: "fat32")
 	-h,  --help			Display this message
 	-d,  --MultiOS_dir <NAME>	Specify a data subdirectory (default: "boot_MultiOS")

Detected devices:
---------------------------------------------
```

It is not clear that `-fs`, `-h` and `-d` are the only options - it looked like there were addition `[options]`.
