### ISSUE TITLE
Read-only partition with extx filesystems

### ISSUE THREAD

**Issue by kidonsky** [Mexit/MultiOS-USB#13]
Hello and thank you for your usefull project !

I installed a first time my USB key on default fs, but Ubuntu complete iso is 5Go… So fat32 is not sufficient.

I installed the tool with ext4 and… the partition is now read-only, I can only write it with sudo rights.

Do you have any idea why ?

Command used to install the tool
`sudo ./multios-usb.sh -f ext4 /dev/sdb 20G`

Thanks !

**Comment by JonnyTech** [comment]
It is ext4 filesystem permissions, try:

```
sudo chown username mountpoint
```
Or
```
sudo chmod 777 mountpoint
```

Alternatively use another filesystem format.

**Comment by kidonsky** [comment]
Thank you !
