### ISSUE TITLE
Super Grub2 Disk support

### ISSUE THREAD

**Issue by JonnyTech** [Mexit/MultiOS-USB#16]
In the same way that MultiOS-USB supports memdisk and similar EFI based boot environments, can support also be added for Super Grub2 Disk (https://github.com/supergrub/supergrub and https://www.supergrubdisk.org/super-grub2-disk/)? EFI images are supplied which _should_ be trivial to support but I am unable to implement. Thank you for your attention.

**Comment by Mexit** [comment]
Just copy the efi file to the EFI folder on the first partition. It is then necessary to change the extension from EFI to efi.
You launch the file from the menu: "Detect EFI bootloaders -->"

Another option is to add items in the main configuration file. Here is an example. Just change the path :)
https://github.com/Mexit/MultiOS-USB/blob/946fc464c7a083ba0ec55eaceaa1cd9f27878951/config/grub.config#L163-L167

**Comment by JonnyTech** [comment]
Thank you very much, that helps immensely.

> You launch the file from the menu: "Detect EFI bootloaders -->"

Aha! I reckon that I was being really dumb...
