### ISSUE TITLE
Compare with Ventoy

### ISSUE THREAD

**Issue by pepa65** [Mexit/MultiOS-USB#20]
This project sounds great. But if you search around for recommendations on the internet, Ventoy always comes up. Could you say something how MultiOS-USB differs in approach, in features, etc.? I think a section in the readme would be very helpful for potential users.

**Comment by Mexit** [comment]
> This project sounds great.

Thanks!

> Could you say something how MultiOS-USB differs in approach, in features, etc.?

MultiOS-USB focuses primarily on simplicity and the ability to create your own configurations, does not inject any files into running systems.

> I think a section in the readme would be very helpful for potential users.

Already exists:
https://github.com/Mexit/MultiOS-USB#features

**Comment by pepa65** [comment]
I guess just more people need to start using it and reporting about it..!
