### ISSUE TITLE
Not all ISO files detected

### ISSUE THREAD

**Issue by JonnyTech** [Mexit/MultiOS-USB#3]
Is it possible to boot undetected files such as a Windows 10 installation ISO? After placing it in the ISOs folder, only some Linux ISO's are detected and displayed. Is it a case of making a config file for the missing images or can I force GRUB to display all files found?

**Comment by JonnyTech** [comment]
Aha, I found the instructions for Windows 10: https://github.com/Mexit/MultiOS-USB/blob/master/config/win10_winPE/windows_support.md

How about other, non-dectected ISOs?

Also have one that shows message that it cannot start in loopback mode: [Supet Grub2 Disk](https://sourceforge.net/projects/supergrub2/files/2.04s1/super_grub2_disk_2.04s1/super_grub2_disk_hybrid_2.04s1.iso/download)

**Comment by JonnyTech** [comment]
I have not figured out how to make an ISO load a configuration file. Do you have a newbie tutorial?

**Comment by jmma98** [comment]
Hi, I'm facing this same issue with clear linux and openmandriva rome isos. 

How do I fix this?
