### ISSUE TITLE
Boot Windows directly from the ISO

### ISSUE THREAD

**Issue by a1ive** [Mexit/MultiOS-USB#4]
Nice project.
I see on [windows_support.md](https://github.com/Mexit/MultiOS-USB/blob/master/config/win10_winPE/windows_support.md) that it says
> Currently, you have to extract the files from the ISO image. In the future, we plan to run Windows directly from the ISO image.

How are you going to implement it? Any good ideas? I might be able to help you.

**Comment by Mexit** [comment]
Thank you very much. I will test it in the coming days.

**Comment by a1ive** [comment]
@Mexit any comments on my solution?

**Comment by Mexit** [comment]
> any comments on my solution?

It works!

At this moment I tested your solution with GRUB without any modifications.

Can your solution work in the BIOS version as well?

**Comment by a1ive** [comment]
> Can your solution work in the BIOS version as well?

No. We can only use `linux16 /wimboot; initrd16 ...`.

**Comment by Mexit** [comment]
I have returned to the subject of wimboot.... Not enough time...
In the meantime, I swapped ubuntu grub for the original grub 2.12.
I am currently actively testing your solution. However, it only works to commit [bb4aa6e06](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=bb4aa6e06ee3877110a1dc0eb0d766ffac978993).
From commit [df16fe97b](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=df16fe97b22873018ed2b7f9001940e4fca625f3) it no longer compiles because the call wrappers have been removed.

Is there still any chance in this case to add wimboot to grub 2.12?

Another problem I've encountered is with the latest `Win11_23H2_English_x64v2.iso`: loading files ends with the message: "cannot load image".
```c
//efiboot.c
if (status != GRUB_EFI_SUCCESS)
    grub_fatal("cannot load image\n");
```

**Comment by a1ive** [comment]
> I have returned to the subject of wimboot.... Not enough time... In the meantime, I swapped ubuntu grub for the original grub 2.12. I am currently actively testing your solution. However, it only works to commit [bb4aa6e06](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=bb4aa6e06ee3877110a1dc0eb0d766ffac978993). From commit [df16fe97b](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=df16fe97b22873018ed2b7f9001940e4fca625f3) it no longer compiles because the call wrappers have been removed.
> 
> Is there still any chance in this case to add wimboot to grub 2.12?
> 
> Another problem I've encountered is with the latest `Win11_23H2_English_x64v2.iso`: loading files ends with the message: "cannot load image".
> 
> ```c
> //efiboot.c
> if (status != GRUB_EFI_SUCCESS)
>     grub_fatal("cannot load image\n");
> ```

GRUB 2.12 has added support for loading initrd using the LoadFile2 protocol on x86 platforms, so you can patch wimboot and boot it.
I have submitted the PR to the wimboot project, but have not gotten a response: https://github.com/ipxe/wimboot/pull/49

**Comment by Mexit** [comment]
Excellent work a1ive!
I did the tests. It works flawlessly. However, there is a problem after enabling SB - it gives me an error:
`couldn't find suitable memory target`.
The same thing happens on the original wimboot, both with SB enabled and disabled.

**Comment by Mexit** [comment]
> please increase the allocated memory

I've thought about that too. Unfortunately it doesn't help.
I checked on VM and physical hardware. This error only occurs when SB is enabled. When turned off, everything works fine.

It may be a bug in GRUB. I found the [code](https://git.savannah.gnu.org/cgit/grub.git/tree/grub-core/lib/relocator.c#n1459) fragment responsible for this:

```c
#ifdef GRUB_MACHINE_EFI
    grub_efi_mmap_iterate (grub_relocator_alloc_chunk_align_iter, &ctx,
			   avoid_efi_boot_services);
#elif defined (__powerpc__) || defined (GRUB_MACHINE_XEN)
    (void) avoid_efi_boot_services;
    grub_machine_mmap_iterate (grub_relocator_alloc_chunk_align_iter, &ctx);
#else
    (void) avoid_efi_boot_services;
    grub_mmap_iterate (grub_relocator_alloc_chunk_align_iter, &ctx);
#endif
    if (!ctx.found)
      return grub_error (GRUB_ERR_BAD_OS, "couldn't find suitable memory target");
  }
```

**Comment by Mexit** [comment]
I was able to extract some information from the boot process.
If SB is enabled, the booting is completely different - no information that it uses the LoadFile2 protocol.
```
#################
#  SB disabled  #
#################

loader/efi/linux.c:102:linux: UEFI stub kernel:
loader/efi/linux.c:103:linux: PE/COFF header @ 00000040
loader/efi/linux.c:132:linux: LoadFile2 initrd loading enabled
loader/efi/linux.c:515:linux: kernel file size: 59776
loader/efi/linux.c:517:linux: kernel numpages: 15
loader/efi/linux.c:534:linux: kernel @ 0x7e1d2000
loader/efi/linux.c:420:linux: Using LoadFile2 initrd loading protocol
loader/efi/linux.c:217:linux: linux command line:
'BOOT_IMAGE=/MultiOS-USB/tools/wimboot-2.7.6-a1ive/wimboot gui'
loader/efi/linux.c:237:linux: starting image 0x7e8f4318


wimboot v2.7.6 -- Windows Imaging Format bootloader -- https://ipxe.org/wimboot

Command line: "BOOT_IMAGE=/MultiOS-USB/tools/wimboot-2.7.6-a1ive/wimboot gui"
...found initrd media device
loader/efi/linux.c:360:linux: Providing initrd via EFI_LOAD_FILE2_PROTOCOL
loader/linux.c:68:linux: newc: Creating path 'bootx64.efi', mode=0100777,
size=1692144
loader/linux.c:68:linux: newc: Creating path 'bcd', mode=0100777, size=16384
loader/linux.c:68:linux: newc: Creating path 'boot.sdi', mode=0100777,
size=3170304
loader/linux.c:68:linux: newc: Creating path 'boot.wim', mode=0100777,
size=533364998
loader/linux.c:68:linux: newc: Creating path 'TRAILER!!!', mode=0, size=0
Using bootx64.efi via 0x59e6e07c len 0x19d1f0
...found bootmgfw.efi file bootx64.efi
Using bcd via 0x5a00b2e0 len 0x4000
...found BCD
Using boot.sdi via 0x5a00f358 len 0x306000
Using boot.wim via 0x5a3153d0 len 0x1fca8106
...found WIM file boot.wim
...patching WIM boot.wim
...patching WIM header at [0x0,0xd0)
...found file "\Windows\Boot\Fonts\segmono_boot.ttf"
Using segmono_boot.ttf via 0x7db85060 len 0xb2f4
...found file "\Windows\Boot\Fonts\segoen_slboot.ttf"
Using segoen_slboot.ttf via 0x7db85150 len 0x1910c
...found file "\Windows\Boot\Fonts\segoe_slboot.ttf"
Using segoe_slboot.ttf via 0x7db85240 len 0x19220
...found file "\Windows\Boot\Fonts\wgl4_boot.ttf"
Using wgl4_boot.ttf via 0x7db85330 len 0xc37c
Read bootx64.efi
Loaded bootx64.efi

#################
###  Windows  ###
#################
```
```
################
#  SB enabled  #
################

loader/efi/linux.c:468:linux: shim_lock enabled, falling back to legacy Linux
kernel loader
lib/relocator.c:114:relocator: relocators_size=12
lib/relocator.c:1252:relocator: min_addr = 0x0, max_addr = 0xffffffffffffffff,
target = 0x100000
lib/relocator.c:431:relocator: trying to allocate in
0x100000-0xffffffffffffffff aligned 0x1 size 0xe000
lib/relocator.c:1201:relocator: allocated: 0x100000+0xe000
lib/relocator.c:1290:relocator: allocated 0x100000/0x100000
lib/relocator.c:1308:relocator: relocators_size=12
lib/relocator.c:1316:relocator: relocators_size=12
lib/relocator.c:1323:relocator: cur = 0x79b7ee00, next = 0x0
loader/i386/linux.c:204:linux: prot_mode_mem = 0x100000, prot_mode_target =
100000, prot_size = e000
loader/i386/linux.c:870:linux: bzImage, setup=0x800, size=0xdf80
loader/i386/linux.c:1111:linux: Initrd at addr 0x17e9f000 which is expected in
ranger 0x12a000 ~ 0x37feffff
lib/relocator.c:1401:relocator: chunks = 0x79b7ee00
lib/relocator.c:431:relocator: trying to allocate in 0x12a000-0x17e9f000
aligned 0x1000 size 0x20150000
lib/relocator.c:1425:relocator: Adjusted limits from 12a000-17e9f000 to
10e000-ffffffffffffffff
lib/relocator.c:431:relocator: trying to allocate in
0x10e000-0xffffffffffffffff aligned 0x1000 size 0x20150000
lib/relocator.c:1201:relocator: allocated: 0x1500000+0x20150000
lib/relocator.c:1481:relocator: relocators_size=12
lib/relocator.c:1489:relocator: relocators_size=12
lib/relocator.c:1495:relocator: cur = 0x7a72ce20, next = 0x79b7ee00
loader/linux.c:68:linux: newc: Creating path 'bootx64.efi', mode=0100777,
size=1692144
loader/linux.c:68:linux: newc: Creating path 'bcd', mode=0100777, size=16384
loader/linux.c:68:linux: newc: Creating path 'boot.sdi', mode=0100777,
size=3170304
loader/linux.c:68:linux: newc: Creating path 'boot.wim', mode=0100777,
size=533364998
loader/linux.c:68:linux: newc: Creating path 'TRAILER!!!', mode=0, size=0
loader/i386/linux.c:1138:linux: Initrd (0x1500000) at 0x1500000,
size=0x2014f554
video/efi_gop.c:388:video: GOP: keeping mode 12
video/efi_gop.c:493:video: GOP: initialising FB @ 0xc0000000 1280x800x32
video/efi_gop.c:520:video: GOP: Success
loader/i386/linux.c:531:linux: real_size = 4000, mmap_size = 2000
loader/i386/linux.c:379:linux: addr = 10000, size = 20000, need_size = 7000
loader/i386/linux.c:379:linux: addr = 50000, size = 37000, need_size = 7000
loader/i386/linux.c:379:linux: addr = 88000, size = 8000, need_size = 7000
loader/i386/linux.c:541:linux: real_mode_target = 89000, real_size = 4000,
efi_mmap_size = 3000
lib/relocator.c:1252:relocator: min_addr = 0x0, max_addr = 0x100000, target =
0x89000
lib/relocator.c:431:relocator: trying to allocate in
0x10e000-0xffffffffffffffff aligned 0x1 size 0x7000
lib/relocator.c:1201:relocator: allocated: 0x7ef8b000+0x7000
lib/relocator.c:1290:relocator: allocated 0x7ef8b000/0x89000
lib/relocator.c:1308:relocator: relocators_size=12
lib/relocator.c:1316:relocator: relocators_size=51
lib/relocator.c:1323:relocator: cur = 0x78310e60, next = 0x7a72ce20
loader/i386/linux.c:564:linux: real_mode_mem = 0x7ef8b000
loader/i386/linux.c:574:linux: code32_start = 0
kern/efi/sb.c:121:efi: UEFI Secure Boot state: Enabled

#################
###  Restart  ###
#################
```

**Comment by a1ive** [comment]
> I was able to extract some information from the boot process. If SB is enabled, the booting is completely different - no information that it uses the LoadFile2 protocol.
> 
> ```
> #################
> #  SB disabled  #
> #################
> 
> loader/efi/linux.c:102:linux: UEFI stub kernel:
> loader/efi/linux.c:103:linux: PE/COFF header @ 00000040
> loader/efi/linux.c:132:linux: LoadFile2 initrd loading enabled
> loader/efi/linux.c:515:linux: kernel file size: 59776
> loader/efi/linux.c:517:linux: kernel numpages: 15
> loader/efi/linux.c:534:linux: kernel @ 0x7e1d2000
> loader/efi/linux.c:420:linux: Using LoadFile2 initrd loading protocol
> loader/efi/linux.c:217:linux: linux command line:
> 'BOOT_IMAGE=/MultiOS-USB/tools/wimboot-2.7.6-a1ive/wimboot gui'
> loader/efi/linux.c:237:linux: starting image 0x7e8f4318
> 
> 
> wimboot v2.7.6 -- Windows Imaging Format bootloader -- https://ipxe.org/wimboot
> 
> Command line: "BOOT_IMAGE=/MultiOS-USB/tools/wimboot-2.7.6-a1ive/wimboot gui"
> ...found initrd media device
> loader/efi/linux.c:360:linux: Providing initrd via EFI_LOAD_FILE2_PROTOCOL
> loader/linux.c:68:linux: newc: Creating path 'bootx64.efi', mode=0100777,
> size=1692144
> loader/linux.c:68:linux: newc: Creating path 'bcd', mode=0100777, size=16384
> loader/linux.c:68:linux: newc: Creating path 'boot.sdi', mode=0100777,
> size=3170304
> loader/linux.c:68:linux: newc: Creating path 'boot.wim', mode=0100777,
> size=533364998
> loader/linux.c:68:linux: newc: Creating path 'TRAILER!!!', mode=0, size=0
> Using bootx64.efi via 0x59e6e07c len 0x19d1f0
> ...found bootmgfw.efi file bootx64.efi
> Using bcd via 0x5a00b2e0 len 0x4000
> ...found BCD
> Using boot.sdi via 0x5a00f358 len 0x306000
> Using boot.wim via 0x5a3153d0 len 0x1fca8106
> ...found WIM file boot.wim
> ...patching WIM boot.wim
> ...patching WIM header at [0x0,0xd0)
> ...found file "\Windows\Boot\Fonts\segmono_boot.ttf"
> Using segmono_boot.ttf via 0x7db85060 len 0xb2f4
> ...found file "\Windows\Boot\Fonts\segoen_slboot.ttf"
> Using segoen_slboot.ttf via 0x7db85150 len 0x1910c
> ...found file "\Windows\Boot\Fonts\segoe_slboot.ttf"
> Using segoe_slboot.ttf via 0x7db85240 len 0x19220
> ...found file "\Windows\Boot\Fonts\wgl4_boot.ttf"
> Using wgl4_boot.ttf via 0x7db85330 len 0xc37c
> Read bootx64.efi
> Loaded bootx64.efi
> 
> #################
> ###  Windows  ###
> #################
> ```
> 
> ```
> ################
> #  SB enabled  #
> ################
> 
> loader/efi/linux.c:468:linux: shim_lock enabled, falling back to legacy Linux
> kernel loader
> lib/relocator.c:114:relocator: relocators_size=12
> lib/relocator.c:1252:relocator: min_addr = 0x0, max_addr = 0xffffffffffffffff,
> target = 0x100000
> lib/relocator.c:431:relocator: trying to allocate in
> 0x100000-0xffffffffffffffff aligned 0x1 size 0xe000
> lib/relocator.c:1201:relocator: allocated: 0x100000+0xe000
> lib/relocator.c:1290:relocator: allocated 0x100000/0x100000
> lib/relocator.c:1308:relocator: relocators_size=12
> lib/relocator.c:1316:relocator: relocators_size=12
> lib/relocator.c:1323:relocator: cur = 0x79b7ee00, next = 0x0
> loader/i386/linux.c:204:linux: prot_mode_mem = 0x100000, prot_mode_target =
> 100000, prot_size = e000
> loader/i386/linux.c:870:linux: bzImage, setup=0x800, size=0xdf80
> loader/i386/linux.c:1111:linux: Initrd at addr 0x17e9f000 which is expected in
> ranger 0x12a000 ~ 0x37feffff
> lib/relocator.c:1401:relocator: chunks = 0x79b7ee00
> lib/relocator.c:431:relocator: trying to allocate in 0x12a000-0x17e9f000
> aligned 0x1000 size 0x20150000
> lib/relocator.c:1425:relocator: Adjusted limits from 12a000-17e9f000 to
> 10e000-ffffffffffffffff
> lib/relocator.c:431:relocator: trying to allocate in
> 0x10e000-0xffffffffffffffff aligned 0x1000 size 0x20150000
> lib/relocator.c:1201:relocator: allocated: 0x1500000+0x20150000
> lib/relocator.c:1481:relocator: relocators_size=12
> lib/relocator.c:1489:relocator: relocators_size=12
> lib/relocator.c:1495:relocator: cur = 0x7a72ce20, next = 0x79b7ee00
> loader/linux.c:68:linux: newc: Creating path 'bootx64.efi', mode=0100777,
> size=1692144
> loader/linux.c:68:linux: newc: Creating path 'bcd', mode=0100777, size=16384
> loader/linux.c:68:linux: newc: Creating path 'boot.sdi', mode=0100777,
> size=3170304
> loader/linux.c:68:linux: newc: Creating path 'boot.wim', mode=0100777,
> size=533364998
> loader/linux.c:68:linux: newc: Creating path 'TRAILER!!!', mode=0, size=0
> loader/i386/linux.c:1138:linux: Initrd (0x1500000) at 0x1500000,
> size=0x2014f554
> video/efi_gop.c:388:video: GOP: keeping mode 12
> video/efi_gop.c:493:video: GOP: initialising FB @ 0xc0000000 1280x800x32
> video/efi_gop.c:520:video: GOP: Success
> loader/i386/linux.c:531:linux: real_size = 4000, mmap_size = 2000
> loader/i386/linux.c:379:linux: addr = 10000, size = 20000, need_size = 7000
> loader/i386/linux.c:379:linux: addr = 50000, size = 37000, need_size = 7000
> loader/i386/linux.c:379:linux: addr = 88000, size = 8000, need_size = 7000
> loader/i386/linux.c:541:linux: real_mode_target = 89000, real_size = 4000,
> efi_mmap_size = 3000
> lib/relocator.c:1252:relocator: min_addr = 0x0, max_addr = 0x100000, target =
> 0x89000
> lib/relocator.c:431:relocator: trying to allocate in
> 0x10e000-0xffffffffffffffff aligned 0x1 size 0x7000
> lib/relocator.c:1201:relocator: allocated: 0x7ef8b000+0x7000
> lib/relocator.c:1290:relocator: allocated 0x7ef8b000/0x89000
> lib/relocator.c:1308:relocator: relocators_size=12
> lib/relocator.c:1316:relocator: relocators_size=51
> lib/relocator.c:1323:relocator: cur = 0x78310e60, next = 0x7a72ce20
> loader/i386/linux.c:564:linux: real_mode_mem = 0x7ef8b000
> loader/i386/linux.c:574:linux: code32_start = 0
> kern/efi/sb.c:121:efi: UEFI Secure Boot state: Enabled
> 
> #################
> ###  Restart  ###
> #################
> ```

You are right. GRUB 2 won't use LoadFile2 if shim is enabled.
https://github.com/rhboot/grub2/blob/9e1b18fc17b623446c1adf0466158c7cf7a58303/grub-core/loader/efi/linux.c#L465

**Comment by Mexit** [comment]
> We should remove this check and sign the wimboot image.

It almost worked:
```
loader/efi/linux.c:102:linux: UEFI stub kernel:
loader/efi/linux.c:103:linux: PE/COFF header @ 00000040
loader/efi/linux.c:132:linux: LoadFile2 initrd loading enabled
loader/efi/linux.c:504:linux: kernel file size: 59776
loader/efi/linux.c:506:linux: kernel numpages: 15
loader/efi/linux.c:523:linux: kernel @ 0x7d12a000
loader/efi/linux.c:420:linux: Using LoadFile2 initrd loading protocol

#################
###  Restart  ###
#################
```

**Comment by a1ive** [comment]
> > We should remove this check and sign the wimboot image.
> 
> It almost worked:
> 
> ```
> loader/efi/linux.c:102:linux: UEFI stub kernel:
> loader/efi/linux.c:103:linux: PE/COFF header @ 00000040
> loader/efi/linux.c:132:linux: LoadFile2 initrd loading enabled
> loader/efi/linux.c:504:linux: kernel file size: 59776
> loader/efi/linux.c:506:linux: kernel numpages: 15
> loader/efi/linux.c:523:linux: kernel @ 0x7d12a000
> loader/efi/linux.c:420:linux: Using LoadFile2 initrd loading protocol
> 
> #############################
> ###  Return to grub menu  ###
> #############################
> ```

https://github.com/rhboot/grub2/commit/6425c12cd77ad51ad24be84c092aefacf0875089

> The LoadImage() provided by the shim does not consult MOK when loading
an image. So, simply signature verification fails when it should not.
This means we cannot use Linux EFI stub to start the kernel when the
shim is loaded.

**Comment by Mexit** [comment]
@a1ive 
Thanks for your help and valuable tips and wimboot patches!

**Comment by daiaji** [comment]
> > I have returned to the subject of wimboot.... Not enough time... In the meantime, I swapped ubuntu grub for the original grub 2.12. I am currently actively testing your solution. However, it only works to commit [bb4aa6e06](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=bb4aa6e06ee3877110a1dc0eb0d766ffac978993). From commit [df16fe97b](https://git.savannah.gnu.org/cgit/grub.git/commit/?id=df16fe97b22873018ed2b7f9001940e4fca625f3) it no longer compiles because the call wrappers have been removed.
> > Is there still any chance in this case to add wimboot to grub 2.12?
> > Another problem I've encountered is with the latest `Win11_23H2_English_x64v2.iso`: loading files ends with the message: "cannot load image".
> > ```c
> > //efiboot.c
> > if (status != GRUB_EFI_SUCCESS)
> >     grub_fatal("cannot load image\n");
> > ```
> 
> GRUB 2.12 has added support for loading initrd using the LoadFile2 protocol on x86 platforms, so you can patch wimboot and boot it. I have submitted the PR to the wimboot project, but have not gotten a response: [ipxe/wimboot#49](https://github.com/ipxe/wimboot/pull/49)

Can I directly load wimbot. efi with grub2 now?

**Comment by Mexit** [comment]
> Can I directly load wimbot with grub2 for efi now?

Yes, you can. EFI with Secure Boot enabled doesn't work at the moment

More info:
- f304158.
- [config/windows](../tree/master/config/windows)
