### ISSUE TITLE
error: device not found

### ISSUE THREAD

**Issue by chacles** [Mexit/MultiOS-USB#5]
![2](https://user-images.githubusercontent.com/26027694/144755283-33d2e0b8-4627-49cd-9ff4-4e9bc3191ae7.jpg)
![3](https://user-images.githubusercontent.com/26027694/144755285-ca66e507-85bc-475f-bec9-c025e49312e3.jpg)
![4](https://user-images.githubusercontent.com/26027694/144755288-9ac546ac-0f6b-4931-941e-d2aab9fb5857.jpg)
1. Three ISO files of linuxmint are correctly recognized.
2. Choose any file -> Enter -> Esc
3. Choose any file again, error: device not found.

How to fix it, thanks.

**Comment by Mexit** [comment]
Please try replacing `menuentry` with `submenu` in the file `/boot_MultiOS/config/grub_loopback/loopback.cfg`

**Comment by chacles** [comment]
Thanks, it works.
