### ISSUE TITLE
This is not a bootable disk. bug?

### ISSUE THREAD

**Issue by chacles** [Mexit/MultiOS-USB#6]
![5](https://user-images.githubusercontent.com/26027694/144785013-cb5dfaa7-e427-4035-b63a-efa15dc4a0b2.jpg)
Tools -> Boot from Hard Disk.

**Comment by Mexit** [comment]
I have corrected it. Thanks.
Let me know if it works for you too.

**Comment by chacles** [comment]
Thanks, it works.
