### ISSUE TITLE
certificate ubuntu 22

### ISSUE THREAD

**Issue by foxhacker0000** [Mexit/MultiOS-USB#8]
ubuntu image file name:
ubuntu-22.10-desktop-amd64.iso

motherboard:
gigabyte z2709-D3

i installed certificate from EFI/BOOT/cert/MultiOS-USB.cer
Select Continue and confirm (Yes) key enrolling
but security violation error
i disabled secure boot but same error again

**Comment by foxhacker0000** [comment]
i did all works like document i dont know why this error

**Comment by Mexit** [comment]
Hi,

With SB disabled, there is no need to install certificates - everything should work.
Turn off SB and check again please.

**Comment by foxhacker0000** [comment]
i disabled SB (secure boot not work)

**Comment by Mexit** [comment]
Check the downloaded image is correct, and the new version of Ubuntu 23.04.
Upload some screenshots of the errors

**Comment by foxhacker0000** [comment]
error image screenshot

![image](https://github.com/Mexit/MultiOS-USB/assets/47057115/18e18ab4-ce91-4f44-9cfc-9a002d91ee9f)

**Comment by JonnyTech** [comment]
https://askubuntu.com/questions/1456460/verification-failed-0x1a-security-violation-while-installing-ubuntu

Please make sure that you fully disable Secure Boot - and try a newer download from Ubuntu.

**Comment by foxhacker0000** [comment]
i did it sir not work

**Comment by Mexit** [comment]
> error image screenshot
> 
> ![image](https://user-images.githubusercontent.com/47057115/246673636-18e18ab4-ce91-4f44-9cfc-9a002d91ee9f.png)

If you see such a message it means that SB is still active.

When disabling SB in the bios, remember to save the settings.

**Comment by foxhacker0000** [comment]
i disabled secure boot and saved
same error again

motherboard:
z270p-d3

**Comment by Mexit** [comment]
Did you manage to get it working?
