### ISSUE TITLE
custom config

### ISSUE THREAD

**Issue by foxhacker0000** [Mexit/MultiOS-USB#9]
can I add my own custom config?
if yes how?

**Comment by Mexit** [comment]
You can store your own configurations in `config_priv` folder.

You do not have to make configurations from scratch. Just copy the one you have selected from the `config` folder and update it according to your needs.

If this is not sufficient (big changes), you can follow the other configuration files

**Comment by Mexit** [comment]
Have you created your own configuration? If you have any questions or problems, I will try to help
